version: '3.5'
services:
  sell_trader:  # Optional SELL_USDT_BTC
    build: .
    container_name: sell_trader # SELL_Optional USDT_BTC
    env_file:
      - .env2
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  buy_trader:
    build: .
    container_name: buy_trader
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
